### ISSUE TITLE
Edit description from straight from the Agenda view 

### ISSUE THREAD

**Issue by jmambu** [crazko/calex-classic#8]
I wonder if you could make one single modification that is a button that allow to EDIT or ADD the description straight from the agenda view instead of clicking it one by one to edit them.

cheers!

**Comment by crazko** [comment]
Shouldn't be that hard to implement.

I just put here some notes so I don't have to remember:

- https://developers.google.com/google-apps/calendar/v3/reference/events/update
- https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content
- edit / save button on a corner
- two divs above each other:
	- source editable
	- result with markdown

**Comment by crazko** [comment]
Development moved here https://github.com/crazko/calex as classic calendar is not available anymore.
